classDiagram
    class Animal:::styleClass
    class Mineral:::styleClass2

    classDef styleClass fill:#f9f,stroke:#333,stroke-width:4px
    classDef styleClass2 fill:#bbf,stroke:#f66,stroke-width:2px
