flowchart TD
    A@{ img: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAABQCAIAAAARP+ljAAABBElEQVR4nO3RywkCQRRFwcnToNybijmYg+DeBAQNQNDF/HoOdTnbhkfX9Hi+FG7a/QKtGuB4gOMBjgc4HuB4gOMBjgc43h/g0/mmwQMcD3A8wPEAxwMcD3A8wPEAxwMcb0Xgt20ywPEBjg9wfIDjAxwf4PgAxzco8O+3WuonAR8gwPEAxwMc75DAttQAxwc4PsDxAY4PcHyA4wMcH+D4BgW+XO+xtuH8HmDAgAEDBgx4nw0KbEsNcHyA4wMcH+D4AMcHOD7A8QGOD3B8gOMDHB/g+HYD1ggBjgc4HuB4gOMBjgc4HuB4gOMBjjcLWEcPcDzA8QDHAxwPcDzA8QDHAxwPcLwPDO31f45rdEcAAAAASUVORK5CYII=", label: "Image", w: 100, h: 100, constraint: "on" }
