%%{init: { 'logLevel': 'debug', 'theme': 'base', 'themeVariables': { 'commitLabelColor': '#ff0000', 'commitLabelBackground': '#00ff00'}} }%%
gitGraph
   commit id: "1"
   commit id: "2"
   branch develop
   commit id: "3"
