%%{init: { 'logLevel': 'debug', 'theme': 'base', 'themeVariables': { 'gitInv0': '#ff0000'}} }%%
gitGraph
   commit id: "1" type: HIGHLIGHT
   commit id: "2"
   branch develop
   commit id: "3" type: HIGHLIGHT
