%%{init: { 'logLevel': 'debug', 'theme': 'base', 'themeVariables': { 'gitBranchLabel0': '#ffffff', 'gitBranchLabel1': '#000000', 'gitBranchLabel2': '#ffff00'}} }%%
gitGraph
   commit id: "1"
   commit id: "2"
   branch develop
   commit id: "3"
   commit id: "4"
   checkout main
   commit id: "5"
   merge develop
   branch branch1
   commit id: "6"
   branch branch2
   commit id: "7"
   branch test4
   commit id: "8"
