%%{init: { 'logLevel': 'debug', 'theme': 'base', 'themeVariables': { 'tagLabelColor': '#ffffff', 'tagLabelBackground': '#ff0000', 'tagLabelBorder': '#000000'}} }%%
gitGraph
   commit id: "1" tag: "v1.0"
   commit id: "2" tag: "v1.1"
