ishikawa-beta
    Blurry Photo
    Process
        Out of focus
        Shutter speed too slow
        Protective film not removed
    User
        Shaky hands
    Equipment
        Dirty lens
        Damaged sensor
    Environment
        Subject moved too quickly
        Too dark
