---
config:
  themeVariables:
    radar:
      axisColor: "#FF0000"
      graticuleColor: "#CCCCCC"
      curveOpacity: 0.5
      curveStrokeWidth: 3
---
radar-beta
  title Custom Radar Styles
  axis A, B, C, D, E
  curve c1{5, 3, 4, 2, 5}
  curve c2{3, 5, 2, 4, 3}
  graticule polygon
  ticks 4
