flowchart LR
    K0[kubectl on fed0cluster1] --> P0["hello-world-...-q2jpm<br/>1/1 Running<br/>default-fedten-vc-a1-default"]
    K1[kubectl on fed1cluster1] --> P1["hello-world-...-9tv7m<br/>1/1 Running<br/>default-fedten-vc-b1-default"]
