sequenceDiagram
    Alice->John: Solid line without arrow
    Alice-->John: Dotted line without arrow
    Alice->>John: Solid line with arrowhead
    Alice-->>John: Dotted line with arrowhead
    Alice-xJohn: Solid line with a cross
    Alice--xJohn: Dotted line with a cross
    Alice-)John: Solid line with an open arrow (async)
    Alice--)John: Dotted line with an open arrow (async)
