stateDiagram-v2
    [*] --> First
    state First {
        [*] --> second
        second --> [*]
    }
    First --> End
    state End {
        [*] --> third
        third --> [*]
    }
    End --> [*]
