---
config:
  theme: base
  themeVariables:
    cScale0: "#845EC2"
    cScale1: "#D65DB1"
    cScale2: "#FF6F91"
    cScale3: "#FF9671"
    cScale4: "#FFC75F"
    cScale5: "#F9F871"
---
timeline
    title Color Themed Timeline
    section Phase 1
        Task 1 : Detail 1
    section Phase 2
        Task 2 : Detail 2
    section Phase 3
        Task 3 : Detail 3
    section Phase 4
        Task 4 : Detail 4
    section Phase 5
        Task 5 : Detail 5
    section Phase 6
        Task 6 : Detail 6
