timeline
    title MermaidChart 2023 Timeline
    section Q1
        Buttet 1 : sub-point 1a
                  : sub-point 1b
                  : sub-point 1c
        Bullet 2 : sub-point 2a
                  : sub-point 2b
    section Q2
        Bullet 3 : sub-point 3a
                  : sub-point 3b
                  : sub-point 3c
        Bullet 4 : sub-point 4a
