timeline
    title Evolution of Web Development
    2000 : HTML
         : CSS
         : JavaScript
    2005 : AJAX
         : jQuery
    2010 : AngularJS
         : Backbone.js
    2015 : React
         : Vue.js
         : Angular
    2020 : Svelte
         : Next.js
