timeline
    title Timeline of Industrial Revolution
    section 17th-20th century
        Industry 1.0 : Machine industry
        Industry 2.0 : Resistance line
    section 21st century
        Industry 3.0 : Internet industry
        Industry 4.0 : Future industry
