journey
    accTitle: My daily workflow diagram
    accDescr: A user journey showing the steps in a typical work day
    title My Daily Workflow
    section Morning
      Check email: 3: Me
      Stand-up meeting: 4: Me, Team
    section Afternoon
      Deep work: 5: Me
      Review PRs: 4: Me, Team
