wardley-beta
title Tea Shop
component Cup of Tea [0.79, 0.61]
component Tea [0.63, 0.81]
component Hot Water [0.63, 0.78]
component Cup [0.49, 0.87]
component Water [0.38, 0.94]
component Kettle [0.52, 0.72]
component Power [0.38, 0.89]
anchor Customer [0.95, 0.63]
Customer -> Cup of Tea
Cup of Tea -> Tea
Cup of Tea -> Hot Water
Hot Water -> Water
Hot Water -> Kettle
Kettle -> Power
evolution Genesis -> Custom -> Product -> Commodity
